class Constants:
    DEFAULT_BUTTON_COLOR = "#90accc"
    PRESSED_BUTTON_COLOR = "#b4d7ff"
    MENU_BUTTON_WIDTH = 255
    MENU_BUTTON_HEIGHT = 60
    TEXT_INPUT_WIDTH = 500
    TEXT_INPUT_HEIGHT = 85
    TEXT_INPUT_BORDER = 1
    TEXT_INPUT_OUTLINE_COLOR = "#000000"
    TEXT_COLOR = "#000000"
    CORRECT_ANSWER_COLOR = "#00ff00"
    WRONG_ANSWER_COLOR = "#ff0000"
